return {
  version = "1.1",
  luaversion = "5.1",
  tiledversion = "0.16.0",
  orientation = "orthogonal",
  renderorder = "right-down",
  width = 64,
  height = 64,
  tilewidth = 32,
  tileheight = 32,
  nextobjectid = 30,
  properties = {},
  tilesets = {
    {
      name = "brickRed03",
      firstgid = 1,
      tilewidth = 32,
      tileheight = 32,
      spacing = 0,
      margin = 0,
      image = "../../toy-bricks/brickRed03.png",
      imagewidth = 32,
      imageheight = 64,
      tileoffset = {
        x = 0,
        y = 0
      },
      properties = {},
      terrains = {},
      tilecount = 2,
      tiles = {}
    }
  },
  layers = {
    {
      type = "objectgroup",
      name = "Слой объектов 1",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      objects = {
        {
          id = 1,
          name = "",
          type = "",
          shape = "rectangle",
          x = 320,
          y = 512,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 1,
          visible = true,
          properties = {}
        },
        {
          id = 2,
          name = "",
          type = "",
          shape = "rectangle",
          x = 352,
          y = 448,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 1,
          visible = true,
          properties = {}
        },
        {
          id = 3,
          name = "",
          type = "",
          shape = "rectangle",
          x = 864,
          y = 320,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 1,
          visible = true,
          properties = {}
        },
        {
          id = 4,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1088,
          y = 448,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 1,
          visible = true,
          properties = {}
        },
        {
          id = 5,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1216,
          y = 576,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 1,
          visible = true,
          properties = {}
        },
        {
          id = 6,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1152,
          y = 768,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 1,
          visible = true,
          properties = {}
        },
        {
          id = 7,
          name = "",
          type = "",
          shape = "rectangle",
          x = 864,
          y = 896,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 1,
          visible = true,
          properties = {}
        },
        {
          id = 8,
          name = "",
          type = "",
          shape = "rectangle",
          x = 640,
          y = 928,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 1,
          visible = true,
          properties = {}
        },
        {
          id = 9,
          name = "",
          type = "",
          shape = "rectangle",
          x = 512,
          y = 928,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 1,
          visible = true,
          properties = {}
        },
        {
          id = 10,
          name = "",
          type = "",
          shape = "rectangle",
          x = 384,
          y = 608,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 1,
          visible = true,
          properties = {}
        },
        {
          id = 11,
          name = "",
          type = "",
          shape = "rectangle",
          x = 800,
          y = 576,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 1,
          visible = true,
          properties = {}
        },
        {
          id = 12,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1056,
          y = 608,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 1,
          visible = true,
          properties = {}
        },
        {
          id = 13,
          name = "",
          type = "",
          shape = "rectangle",
          x = 640,
          y = 288,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 1,
          visible = true,
          properties = {}
        },
        {
          id = 14,
          name = "",
          type = "",
          shape = "rectangle",
          x = 256,
          y = 256,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 1,
          visible = true,
          properties = {}
        },
        {
          id = 15,
          name = "",
          type = "",
          shape = "rectangle",
          x = 96,
          y = 352,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 1,
          visible = true,
          properties = {}
        },
        {
          id = 16,
          name = "",
          type = "",
          shape = "rectangle",
          x = 160,
          y = 544,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 1,
          visible = true,
          properties = {}
        },
        {
          id = 17,
          name = "",
          type = "",
          shape = "rectangle",
          x = 256,
          y = 704,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 1,
          visible = true,
          properties = {}
        },
        {
          id = 18,
          name = "",
          type = "",
          shape = "rectangle",
          x = 320,
          y = 768,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 1,
          visible = true,
          properties = {}
        },
        {
          id = 19,
          name = "",
          type = "",
          shape = "rectangle",
          x = 864,
          y = 928,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 1,
          visible = true,
          properties = {}
        },
        {
          id = 20,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1184,
          y = 896,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 1,
          visible = true,
          properties = {}
        },
        {
          id = 21,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1216,
          y = 640,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 1,
          visible = true,
          properties = {}
        },
        {
          id = 22,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1248,
          y = 416,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 1,
          visible = true,
          properties = {}
        },
        {
          id = 23,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1120,
          y = 288,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 1,
          visible = true,
          properties = {}
        },
        {
          id = 24,
          name = "",
          type = "",
          shape = "rectangle",
          x = 704,
          y = 224,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 1,
          visible = true,
          properties = {}
        },
        {
          id = 25,
          name = "",
          type = "",
          shape = "rectangle",
          x = 480,
          y = 224,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 1,
          visible = true,
          properties = {}
        },
        {
          id = 26,
          name = "",
          type = "",
          shape = "rectangle",
          x = 480,
          y = 416,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 1,
          visible = true,
          properties = {}
        },
        {
          id = 27,
          name = "",
          type = "",
          shape = "rectangle",
          x = 608,
          y = 576,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 1,
          visible = true,
          properties = {}
        },
        {
          id = 28,
          name = "",
          type = "",
          shape = "rectangle",
          x = 704,
          y = 704,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 1,
          visible = true,
          properties = {}
        },
        {
          id = 29,
          name = "",
          type = "",
          shape = "rectangle",
          x = 640,
          y = 864,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 1,
          visible = true,
          properties = {}
        }
      }
    }
  }
}
